using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using Unity.VisualScripting;
using UnityEngine;
using static UnityEngine.ParticleSystem;

/// <summary>
/// ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ÌƒXï¿½sï¿½[ï¿½hï¿½ï¿½Ï‚ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½X
/// </summary>
public class Particle_Transform : MonoBehaviour
{

    [SerializeField]private float Po1;
    [SerializeField] private float Po2;
    [SerializeField] private float Po3;
    [SerializeField] private float Po4;
    [SerializeField] private float Po5;
    [SerializeField] private float Po6;

    [SerializeField] private GameObject Particle;
    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;//ï¿½Aï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‹ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½l
    [SerializeField] private float StartOut;
    [SerializeField] private float StartIn1;
    [SerializeField] private float StartIn2;
    [SerializeField] private float StartIn3;
    [SerializeField] private float StartIn4;
    [SerializeField] private float StartIn5;

    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;
    

    //=================================================================================
    //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //=================================================================================

    private void Start()
    {
        Particle.SetActive(false);
    }

    //=================================================================================
    //ï¿½Cï¿½xï¿½ï¿½ï¿½g
    //=================================================================================

    

    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½
        Vector3 position = Particle.transform.position;

        if (StartOut <= DisZ && DisZ < StartIn && Hit.hit)
        {
            Particle.SetActive(true);
            position.y = Po1;
            Particle.transform.position = position;
            
            if (StartOut <= DisZ && DisZ < StartIn1)
            {
                position.y = Po2;
                Particle.transform.position = position;
            }
            if (StartOut <= DisZ && DisZ < StartIn2)
            {
                position.y = Po3;
                Particle.transform.position = position;
            }
            if (StartOut <= DisZ && DisZ < StartIn3)
            {
                position.y = Po4;
                Particle.transform.position = position;
            }
            if (StartOut <= DisZ && DisZ < StartIn4)
            {
                position.y = Po5;
                Particle.transform.position = position;
            }
            if (StartOut <= DisZ && DisZ < StartIn5)
            {
                position.y = Po6;
                Particle.transform.position = position;
            }
        
        }

        if (DisZ < StartOut || !Hit.hit)
        {
            Particle.SetActive(false);
        position.y = Po1;
            Particle.transform.position = position;
        }

    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }

}