using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using Unity.VisualScripting;
using UnityEngine;
using static UnityEngine.ParticleSystem;

/// <summary>
/// ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ÌƒXï¿½sï¿½[ï¿½hï¿½ï¿½Ï‚ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½X
/// </summary>
public class ParticleSpeed : MonoBehaviour
{

    [SerializeField]private float _speed1;
    [SerializeField] private float _speed2;
    [SerializeField] private float _speed3;
    [SerializeField] private float _speed4;
    [SerializeField] private float _speed5;
    [SerializeField] private float _speed6;

    [SerializeField] private GameObject Particle;
    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;//ï¿½Aï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‹ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½l
    [SerializeField] private float StartOut;
    [SerializeField] private float StartIn1;
    [SerializeField] private float StartIn2;
    [SerializeField] private float StartIn3;
    [SerializeField] private float StartIn4;
    [SerializeField] private float StartIn5;

    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;

    [SerializeField] ParticleSystem particle;

    //=================================================================================
    //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //=================================================================================

    private void Start()
    {
        Particle.SetActive(false);
    }

    //=================================================================================
    //ï¿½Cï¿½xï¿½ï¿½ï¿½g
    //=================================================================================

    

    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½

        if (StartOut <= DisZ && DisZ < StartIn && Hit.hit)
        {
            Particle.SetActive(true);
            ChangeSpeed(particle, _speed1);
            
            if (StartOut <= DisZ && DisZ < StartIn1)
            {
                 ChangeSpeed(particle, _speed2);
                  
            }
            if (StartOut <= DisZ && DisZ < StartIn2)
            {
                 ChangeSpeed(particle, _speed3);

            }
            if (StartOut <= DisZ && DisZ < StartIn3)
            {
                 ChangeSpeed(particle, _speed4);

            }
            if (StartOut <= DisZ && DisZ < StartIn4)
            {
                 ChangeSpeed(particle, _speed5);

            }
            if (StartOut <= DisZ && DisZ < StartIn5)
            {
                 ChangeSpeed(particle, _speed6);

            }
        
        }

        if (DisZ < StartOut || !Hit.hit)
        {
            Particle.SetActive(false);
            ChangeSpeed(particle, _speed1);
        }

    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }

    //=================================================================================
    //ï¿½ÏX
    //=================================================================================

    //ï¿½wï¿½è‚µï¿½ï¿½ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½ï¿½ÏX
    private void ChangeSpeed(ParticleSystem particle, float speed)
    {
        var velocity = particle.velocityOverLifetime;
        velocity.speedModifier = speed;
    }

}