using System.Collections.Generic;
using System.Collections;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using static UnityEngine.ParticleSystem;

public class Smo_Color_Changer : MonoBehaviour
{


    [SerializeField] private GameObject Particle;

    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;//ï¿½Aï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‹ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½l
    [SerializeField] private float StartOut;
    [SerializeField] private float StartIn1;
    [SerializeField] private float StartIn2;
    [SerializeField] private float StartIn3;
    [SerializeField] private float StartIn4;
    [SerializeField] private float StartIn5;

    [SerializeField] private float C_R1;
    [SerializeField] private float C_R2;
    [SerializeField] private float C_R3;
    [SerializeField] private float C_R4;
    [SerializeField] private float C_R5;
    [SerializeField] private float C_R6;


    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;

    [SerializeField] ParticleSystem RedParticle;
    Color color;
    
    private void Start()
    {
        Particle.SetActive(false);
        color = RedParticle.startColor;
    }

    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½


        if (StartOut <= DisZ && DisZ < StartIn && Hit.hit)
        {
            Particle.SetActive(true);

            /*if(color.r < 1.0f)
            {
                Color c = color;
                c.r += 0.002f;
                color = c;
        
            }*/

            Color c = color;
            c.r = C_R1;
            color = c;

            ColorChange(RedParticle, color);
            if (StartOut <= DisZ && DisZ < StartIn1)
            {
                c = color;
                c.r = C_R2;
                color = c;
                ColorChange(RedParticle, color);

            }
            if (StartOut <= DisZ && DisZ < StartIn2)
            {
                c = color;
                c.r = C_R3;
                color = c;
                ColorChange(RedParticle, color);

            }
            if (StartOut <= DisZ && DisZ < StartIn3)
            {
                c = color;
                c.r = C_R4;
                color = c;
                ColorChange(RedParticle, color);

            }
            if (StartOut <= DisZ && DisZ < StartIn4)
            {
                c = color;
                c.r = C_R5;
                color = c;
                ColorChange(RedParticle, color);

            }
            if (StartOut <= DisZ && DisZ < StartIn5)
            {
                c = color;
                c.r = C_R6;
                color = c;
                ColorChange(RedParticle, color);

            }
        }

        if (DisZ < StartOut || !Hit.hit)
        {
            Particle.SetActive(false);
            Color c = color;
            c.r = 0;
            color = c;
        }

    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }

    

    private void ColorChange(ParticleSystem particle, Color color)
    {
        
        var main = particle.main;
        main.startColor = new ParticleSystem.MinMaxGradient(color);
    }

}
