using UnityEngine;
using System.Net.Sockets;
using System.Text;
using System;
using System.Threading;
using System.Net;

public class Perche_move : MonoBehaviour
{
    private string host = "driving-hamada.local";//ï¿½ï¿½ï¿½Yï¿½pï¿½Cï¿½Ìİ’è‚©ï¿½ï¿½mï¿½Fï¿½Å‚ï¿½ï¿½ï¿½zï¿½Xï¿½gï¿½ï¿½
    //ï¿½ï¿½ï¿½Yï¿½pï¿½Cï¿½Ö‚Ì‘ï¿½ï¿½Mï¿½|ï¿½[ï¿½g
    private int port = 60000;//ï¿½ï¿½ï¿½Yï¿½pï¿½Cï¿½Ìï¿½ï¿½Eï¿½ï¿½_UDPï¿½pï¿½vï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Ìƒ|ï¿½[ï¿½gï¿½Ôï¿½
    private UdpClient client;
    public int Target_Temperature;
    public int Target_Time;
    private int Peltier_OFF = 0;
    private int Peltier_ON = 1;

    //ï¿½ï¿½ï¿½Yï¿½pï¿½Cï¿½ï¿½ï¿½ï¿½Ìï¿½Mï¿½pï¿½|ï¿½[ï¿½g
    private UdpClient receiveClient;
    private Thread receiveThread;
    private int receivePort = 5005;
    private bool isRunning = true;//ï¿½ï¿½Mï¿½Xï¿½ï¿½ï¿½bï¿½hï¿½Ìï¿½ï¿½sï¿½ï¿½ï¿½
    public float temperature;

    void Start()
    {
        client = new UdpClient();
        client.Connect(host, port);

        /*receiveClient = new UdpClient(receivePort);
        receiveThread = new Thread(new ThreadStart(ReceiveData));
        receiveThread.IsBackground = true;
        receiveThread.Start();*/
    }


    void Update()
    {
        if (Hit_Bike.perche_Active)//ï¿½ï¿½ï¿½ß‚Éƒoï¿½Cï¿½Nï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½Cï¿½~ï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½Lï¿½^
        {
            Debug.Log("Send");
            Debug.Log("é€ä¿¡ã™ã‚‹Target_Time: " + Target_Time);
            byte[] message = new byte[12];//4ï¿½oï¿½Cï¿½g(Peltier_ON)+4ï¿½oï¿½Cï¿½g(Target_Temperature)
            Buffer.BlockCopy(BitConverter.GetBytes(Peltier_ON), 0, message, 0, 4);
            Buffer.BlockCopy(BitConverter.GetBytes(Target_Temperature), 0, message, 4, 4);
            Buffer.BlockCopy(BitConverter.GetBytes(Target_Time), 0, message, 8, 4);
            client.Send(message, message.Length);
            Hit_Bike.perche_Active = false;

        }


        /*if (Input.GetKeyDown(KeyCode.S))
        {
            Debug.Log("Send");
            byte[] message = new byte[12];//4ï¿½oï¿½Cï¿½g(Peltier_ON)+4ï¿½oï¿½Cï¿½g(Target_Temperature)
            Buffer.BlockCopy(BitConverter.GetBytes(Peltier_ON), 0, message, 0, 4);
            Buffer.BlockCopy(BitConverter.GetBytes(Target_Temperature), 0, message, 4, 4);
            Buffer.BlockCopy(BitConverter.GetBytes(Target_Time), 0, message, 8, 4);
            //var message = BitConverter.GetBytes(Peltier_ON);
            //var message = Encoding.UTF8.GetBytes("Hello World!");
            client.Send(message, message.Length);
        }

        else if (Input.GetKeyDown(KeyCode.A))
        {
            Debug.Log("Send");
            byte[] message = new byte[12];//4ï¿½oï¿½Cï¿½g(Peltier_OFF)+4ï¿½oï¿½Cï¿½g(Target_Temperature)
            Buffer.BlockCopy(BitConverter.GetBytes(Peltier_OFF), 0, message, 0, 4);
            Buffer.BlockCopy(BitConverter.GetBytes(Target_Temperature), 0, message, 4, 4);
            Buffer.BlockCopy(BitConverter.GetBytes(Target_Time), 0, message, 8, 4);
            //var message = BitConverter.GetBytes(Peltier_OFF);
            client.Send(message, message.Length);
        }*/
    }
    /*private void ReceiveData()
    {
        IPEndPoint anyIP = new IPEndPoint(IPAddress.Parse("192.168.11.64"), receivePort);

        while (isRunning) // isRunningï¿½ï¿½trueï¿½ÌŠÔAï¿½ï¿½Mï¿½ğ‘±‚ï¿½ï¿½ï¿½
        {
            if (receiveClient.Available > 0)
            {
                byte[] data = receiveClient.Receive(ref anyIP);
                string message = Encoding.UTF8.GetString(data);
                float.TryParse(message, out temperature);
                Debug.Log("Temperature: " + temperature.ToString("F2") + " â„ƒ");
            }
            else
            {
                Debug.Log("ãƒ‡ãƒ¼ã‚¿ãŒå–å¾—ã§ãã¾ã›ã‚“ã§ã—ãŸ");
            }
        }
    }*/

    private void OnDestroy()
    {
        isRunning = false;//ï¿½Xï¿½ï¿½ï¿½bï¿½hï¿½ï¿½ï¿½[ï¿½vï¿½ï¿½ï¿½Iï¿½ï¿½
        if(client == null){
            return;
        }
       
        client.Close();

        if(receiveClient == null){
            return;
        }
        receiveClient.Close();
    }
}
