using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

public class BikeShadow : MonoBehaviour
{
    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;//ï¿½Aï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‹ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½l
    [SerializeField] private float StartOut;
    [SerializeField] GameObject Carframe;
    Renderer CarframeMaterial;

    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;


    public GameObject Shadow;

    // Start is called before the first frame update
    void Start()
    {
        CarframeMaterial = Carframe.GetComponent<MeshRenderer>();
        Shadow.SetActive(false);
        CarframeMaterial.sharedMaterial.DisableKeyword("_EMISSION");

    }

    // Update is called once per frame
    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½

            if (StartOut <= DisZ && DisZ < StartIn && Hit.hit)
            {
                CarframeMaterial.sharedMaterial.EnableKeyword("_EMISSION");//ï¿½hï¿½Aï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ğ”­Œï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                Shadow.SetActive(true);

            }

            if (DisZ < StartOut || !Hit.hit)
            {
                CarframeMaterial.sharedMaterial.DisableKeyword("_EMISSION");
                Shadow.SetActive(false);
            }
        
    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }


}
