using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Hit : MonoBehaviour
{
    //ï¿½Õ“Ë‚ï¿½ï¿½Ä‚ï¿½Ô‚Ì‚İ•\ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½É‚ï¿½ï¿½é‚½ï¿½ß‚ÌƒXï¿½Nï¿½ï¿½ï¿½vï¿½g
    public static bool hit;

    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½
        //Debug.Log(DisZ);
    }

    // Update is called once per frame
    void OnTriggerStay(Collider collider)//ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ô‚Ì‚İ•\ï¿½ï¿½ï¿½ÌƒIï¿½ï¿½ï¿½Iï¿½tï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
    {
        if (collider.gameObject.tag == "CurveTarget")
        {

            hit = true;

        }

    }

    void OnTriggerExit(Collider collider)
    {
        if (collider.gameObject.tag == "CurveTarget")
        {
          
            hit = false;

        }

    }

     float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }

}
