using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using static UnityEngine.ParticleSystem;



public class Spider : MonoBehaviour
{
    public enum HyogenType
    {
        Spider_Normal,
        Spider_Ougi,
    }
    [SerializeField] private  HyogenType m_HasuType = HyogenType.Spider_Normal;
    public GameObject[] signs;
    private GameObject Particle;

    private List<ParticleSystem> _particleSystems;
    [SerializeField] private float _spped;

    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;
    [SerializeField] private float StartOut;


    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;
    private float DisZ;
    private float rad;


    private void Start()
    {
        switch (m_HasuType)
        {
            case HyogenType.Spider_Normal:
                Particle = signs[0];
                break;

            case HyogenType.Spider_Ougi:
                Particle = signs[1];
                break;

        }
        
        Particle.SetActive(false);
        _particleSystems = Particle.GetComponentsInChildren<ParticleSystem>().ToList();
    }



    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½


        if (StartOut <= DisZ && DisZ < StartIn && Hit.hit)
        {
            Particle.SetActive(true);
            
        }

        if (DisZ < StartOut || !Hit.hit)
        {
            Particle.SetActive(false);
            Hit.hit = false;
        }

    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }

    //ï¿½wï¿½è‚µï¿½ï¿½ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½ï¿½ÏX
    private void ChangeSpeed(ParticleSystem particle, float speed)
    {
        var main = particle.main;
        main.simulationSpeed = speed;
    }

}
