using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class CycleShadow : MonoBehaviour
{
    [SerializeField] GameObject Shadow;
    [SerializeField] Transform ShadowT;
    [SerializeField] GameObject ShadowLight;
    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;//ï¿½Aï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‹ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½l
    [SerializeField] private float StartOut;


    Vector3 CarP;
    Vector3 TargetP;
    Vector3 size = new Vector3(0, 0, 0);

    private float disZ;
    private float DisZ;
    private float rad;
    private float zvalue = 1.203f;
    private float dx = 0.02f;
    private float dy = 0.03f;
    private float dz = 0.03f;
    private bool human;

    // Start is called before the first frame update
    void Start()
    {
        Shadow.SetActive(false);
        ShadowLight.SetActive(false);
        ShadowT.transform.localPosition = new Vector3(0.586f, 0.989f, 1.203f);//ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½É–ß‚ï¿½
    }

    // Update is called once per frame
    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½

    
        if (StartOut <= DisZ && DisZ < StartIn && human)
        {
            //ï¿½eï¿½Æƒï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
            Shadow.gameObject.SetActive(true);
            ShadowLight.SetActive(true);

            //ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½
            zvalue -= 0.012f;
            Vector3 pos = new Vector3(0.586f,0.989f,zvalue);
            ShadowT.transform.localPosition = pos;

            //ï¿½eï¿½ï¿½ï¿½gï¿½å‚·ï¿½ï¿½
       
            size.y += dy*Time.deltaTime;;
            size.z += dz*Time.deltaTime;;
            ShadowT.transform.localScale = size;

            if (zvalue <= 0.55f)
            {
                zvalue = 1.203f;
                ShadowT.transform.localPosition = new Vector3(0.586f, 0.989f, 1.203f);//ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½É–ß‚ï¿½

                if (size.y > 0.06f)
                {

                    size = new Vector3(0, 0, 0);
                    ShadowT.transform.localScale = size;

                }
            }

        }
        if (DisZ < StartOut || !human)
        {
            Shadow.SetActive(false);
            ShadowLight.SetActive(false);

        }
    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }
    void OnTriggerStay(Collider collider)//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½Ê‰ß”ï¿½ï¿½ï¿½
    {
        if (collider.gameObject.tag == "CurveTarget")
        {
            //ï¿½eï¿½Æƒï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
            human = true;

        }
    }

    void OnTriggerExit(Collider collider)//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½Ê‰ß”ï¿½ï¿½ï¿½
    {
        if (collider.gameObject.tag == "CurveTarget")
        {
            //ï¿½eï¿½Æƒï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½Iï¿½tï¿½É‚ï¿½ï¿½ï¿½
            human = false;

        }
    }
}