using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;
using System.Linq;

public class Taikosya3 : MonoBehaviour
{
   
    [SerializeField] private float StartSpeed;
    [SerializeField] Transform Car;

    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    //å³æŠ˜ãƒ©ã‚¤ãƒˆ
    [SerializeField] GameObject Right_move;

    Vector3 CarP;
    Vector3 TargetP;

    public static bool stop;//ãƒã‚¶ãƒ¼ãƒ‰å‡ºç¾ç”¨
    public static bool Rstart;//å³æŠ˜é–‹å§‹ç”¨
    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;
    private float CarSpeed;

    // Start is called before the first frame update
    void Start()
    {
        CarSpeed = StartSpeed;
    }

    // Update is called once per frame
    void Update()
    {
        TargetP = target.transform.position;
        CarP = car.transform.position;

        disZ = Vector3.Distance(TargetP, CarP);//ï¿½Ô‚Æƒnï¿½Uï¿½[ï¿½hï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ğ‘ª’ï¿½
        rad = GetAngle(TargetP, CarP);//ï¿½nï¿½Uï¿½[ï¿½hï¿½Æ‚ÌŠpï¿½xï¿½ï¿½ï¿½Zï¿½o
        DisZ = disZ * Mathf.Sin(rad);//Sinï¿½Öï¿½ï¿½Å‹ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½

        if(DisZ < 20){
            CarSpeed = (StartSpeed/10)*-DisZ - StartSpeed;
            Right_move.SetActive(true);
        }

        Vector3 now2 = this.transform.position;            
        now2 += new Vector3(0.0f, 0.0f, -CarSpeed/3.6f*Time.deltaTime);  
        this.transform.position = now2;

        
    
    }

    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }

}