using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

public class HumanStamp1 : MonoBehaviour
{  public enum HyogenType
    {
        Up,
        Middle,
        Down,
        SizeDown
    }
    [SerializeField] private HyogenType RedType = HyogenType.Middle;
    public GameObject[] signs;
    private GameObject Hyogen;

    [SerializeField] GameObject target;
    [SerializeField] GameObject car;
    [SerializeField] private float StartIn;//ï¿½Aï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚Ì‹ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½l
    [SerializeField] private float StartOut;
    [SerializeField] GameObject Carframe;
    Renderer CarframeMaterial;

    Vector3 CarP;
    Vector3 TargetP;

    private float disZ;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p
    private float DisZ;
    private float rad;

    // Start is called before the first frame update
    void Start()
    {
        switch (RedType)
        {
            case HyogenType.Up:
                Hyogen = signs[0];
                break;

            case HyogenType.Middle:
                Hyogen = signs[1];
                break;

            case HyogenType.Down:
                Hyogen = signs[2];
                break;

            case HyogenType.SizeDown:
                Hyogen = signs[3];
                break;

        }

        CarframeMaterial = Carframe.GetComponent<MeshRenderer>();
        Hyogen.SetActive(false);
        CarframeMaterial.sharedMaterial.DisableKeyword("_EMISSION");

    }

    // Update is called once per frame
    void Update()
    {
        

        if (Input.GetKeyDown(KeyCode.A))
        {
            CarframeMaterial.sharedMaterial.EnableKeyword("_EMISSION");//ï¿½hï¿½Aï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ğ”­Œï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            //OnAnim = true;
            //animator.SetBool("Human", OnAnim);//ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½

            Hyogen.SetActive(true);

        }

        if (Input.GetKeyDown(KeyCode.B))
        {
            CarframeMaterial.sharedMaterial.DisableKeyword("_EMISSION");
            Hyogen.SetActive(false);
        }

    }

    //ï¿½ï¿½_ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Öï¿½
    float GetAngle(Vector3 TargetP, Vector3 CarP)
    {
        Vector3 dt = TargetP - CarP;
        float rad = Mathf.Atan2(dt.z, dt.x);
        return rad;
    }


}